"""Data models for sentinel contract monitoring."""

from __future__ import annotations

from datetime import datetime, timezone

from pydantic import BaseModel, Field
from shared.models import AlertSeverity


class ContractWatch(BaseModel):
    """A contract to monitor."""

    address: str
    chain_id: int = 1
    name: str = ""
    alert_thresholds: dict[str, float] = Field(default_factory=dict)


class WatchConfig(BaseModel):
    """Top-level monitoring configuration."""

    contracts: list[ContractWatch] = Field(default_factory=list)
    poll_interval_seconds: int = 300
    alert_webhook: str | None = None


class Transaction(BaseModel):
    """A blockchain transaction."""

    hash: str
    from_address: str
    to_address: str | None
    value_wei: int
    method_id: str | None = None
    block_number: int
    timestamp: datetime


class Alert(BaseModel):
    """An alert generated by a rule evaluation."""

    contract: ContractWatch
    severity: AlertSeverity
    rule_name: str
    message: str
    tx_hash: str | None = None
    value: float | None = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
